name: 1.0
pool:
  vmImage: ubuntu-latest
trigger:
  - main
variables:
  - group: AWS
  - group: Azure
stages:
  - stage: validate
    displayName: Terraform Validate
    jobs:
      - job: validate
        displayName: Terraform Validate
        steps:
          - script: | 
              terraform init
              terraform validate
            displayName: Terraform Validate
            env:
              AWS_ACCESS_KEY: $(AWS_ACCESS_KEY)
              AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
              ARM_CLIENT_ID: $(ARM_CLIENT_ID)
              ARM_TENANT_ID: $(ARM_TENANT_ID)
              ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
              ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)

  - stage: plan
    displayName: Terraform Plan
    jobs:
      - job: plan
        displayName: Terraform Plan
        steps:
          - task: DownloadSecureFile@1
            name: aws_key_pub
            displayName: Download AWS Public Key
            inputs:
              secureFile: aws.key.pub
          - task: DownloadSecureFile@1
            name: azure_key_pub
            displayName: Download Azure Public Key
            inputs:
              secureFile: azure.key.pub
          - script: | 
              terraform init
              terraform plan -out=plan.out
            displayName: Terraform Plan
            env:
              AWS_ACCESS_KEY: $(AWS_ACCESS_KEY)
              AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
              ARM_CLIENT_ID: $(ARM_CLIENT_ID)
              ARM_TENANT_ID: $(ARM_TENANT_ID)
              ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
              ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
              TF_VAR_aws_key_pub: $(aws_key_pub.secureFilePath)
              TF_VAR_azure_key_pub: $(azure_key_pub.secureFilePath)
          - publish: $(Build.SourcesDirectory)/plan.out
            artifact: plan
            displayName: Publish Plan

  - stage: approve_apply
    displayName: Approve Apply
    jobs:
      - job: approve_apply
        pool: server
        displayName: Approve Apply
        steps:
          - task: ManualValidation@0
            timeoutInMinutes: 10

  - stage: apply
    displayName: Terraform Apply
    jobs:
      - job: apply
        displayName: Terraform Apply
        steps:
          - task: DownloadSecureFile@1
            name: aws_key_pub
            displayName: Download AWS Public Key
            inputs:
              secureFile: aws.key.pub
          - task: DownloadSecureFile@1
            name: azure_key_pub
            displayName: Download Azure Public Key
            inputs:
              secureFile: azure.key.pub
          - download: current
            artifact: plan
            displayName: Download Plan
          - script: | 
              terraform init
              terraform apply $(Pipeline.workspace)/plan/plan.out
            displayName: Terraform Plan
            env:
              AWS_ACCESS_KEY: $(AWS_ACCESS_KEY)
              AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
              ARM_CLIENT_ID: $(ARM_CLIENT_ID)
              ARM_TENANT_ID: $(ARM_TENANT_ID)
              ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
              ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
              TF_VAR_aws_key_pub: $(aws_key_pub.secureFilePath)
              TF_VAR_azure_key_pub: $(azure_key_pub.secureFilePath)

  - stage: approve_destroy
    displayName: Approve Destroy
    jobs:
      - job: approve_destroy
        pool: server
        displayName: Approve Destroy
        steps:
          - task: ManualValidation@0
            timeoutInMinutes: 10

  - stage: destroy
    displayName: Terraform Destroy
    jobs:
      - job: destroy
        displayName: Terraform Destroy
        steps:
          - task: DownloadSecureFile@1
            name: aws_key_pub
            displayName: Download AWS Public Key
            inputs:
              secureFile: aws.key.pub
          - task: DownloadSecureFile@1
            name: azure_key_pub
            displayName: Download Azure Public Key
            inputs:
              secureFile: azure.key.pub
          - script: | 
              terraform init
              terraform destroy -auto-approve
            displayName: Terraform Destroy
            env:
              AWS_ACCESS_KEY: $(AWS_ACCESS_KEY)
              AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
              ARM_CLIENT_ID: $(ARM_CLIENT_ID)
              ARM_TENANT_ID: $(ARM_TENANT_ID)
              ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
              ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
              TF_VAR_aws_key_pub: $(aws_key_pub.secureFilePath)
              TF_VAR_azure_key_pub: $(azure_key_pub.secureFilePath)